services:
  postgres_db_greenprep:
    image: postgres:17.4
    container_name: greenprep_db_local
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: greenprep_app_local
    ports:
      - 3010:3010
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres_db_greenprep
  pgadmin:
    container_name: pgadmin4_greenprep
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      - postgres_db_greenprep

volumes:
  postgres_data: {}
